cargo-insta: sort snapshots by name
mitsuhiko/insta pull request #405
Opened 2023-09-16 01:22 UTC by marcospb19

2023-09-16 01:31 UTC, marcospb19 commented on cargo-insta/src/cli.rs
> +    snapshot_containers.sort_by(|(a, _), (b, _)| a.snapshot_path().cmp(&b.snapshot_path()));
This is incredibly helpful for multiple snapshots that come from the same test.

However, it shows them in an odd order:
```
  tests/ui.rs (ui_test_err_missing_files-2)
  tests/ui.rs (ui_test_err_missing_files-3)
  tests/ui.rs (ui_test_err_missing_files-4)
  tests/ui.rs (ui_test_err_missing_files)
```

As a plus, it also groups together snapshots from functions with the same prefix.

2023-10-08 03:37 UTC, marcospb19 commented
Force-pushing to retrigger tests.

2023-10-08 10:46 UTC, mitsuhiko commented
I'm in favor of this change but I would probably add a custom comparison function that detects integer suffixes. If you have more than 10 files it will also sort incorrectly / unexpectedly.

Maybe something like this:

```rust
snapshots.sort_by_key(|x| {
    let mut pieces = x.rsplitn(1, '-');
    if let Some(num_suffix) = pieces.next().and_then(|x| x.parse::<i64>().ok()) {
        (pieces.next().unwrap_or(""), num_suffix)
    } else {
        (*x, 0)
    }
});
```

2023-10-08 10:47 UTC, mitsuhiko requested changes
Sorting is reasonable, but it would be better to sort properly in the actual snapshot order.

2023-10-09 21:20 UTC, closed without merging